### ISSUE TITLE
Entity ID in System hooks

### ISSUE THREAD

**Issue by Ithamar** [Luftare/Ecs#2]
It seems the only way to access the entity id from the system hooks is using _currentEntity, which feels dirty ;) The id is very useful for keeping mappings in the system, e.g. keeping a list of (Bullet/AmmoJS) rigid bodies for the Physics system.

Besides that, my compliments for the design, I **really** like this ECS!

**Comment by Luftare** [comment]
Thank you for the feedback! There's actually another way of accessing the current entity during the run cycle by including additional parameter after the last component parameter in the "every" method. See the global arguments section of the readme to see how it's done.

This whole repo needs quite a bit of brushing up anyway including the documentation. Any contributions are welcome :)

**Comment by Ithamar** [comment]
ah I see I missed that, thanks for the heads up. If you are serious about maintaining this project, I am more then willing to see if I can find some time to contribute too!

Would love to see this available as a npm package for example 😄 

I previously used [yagl/ecs](https://github.com/yagl/ecs) but although the ES6-isms are nice, I prefer your design over that (and that seems to have been abandoned by the author).
